### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-query#15]
@ramyaragupathy and I are sprinting on September 21 - 22 to get osm-query beta out. 
This includes, in order of priority:
1. [x] Gracefully manage datetime inputs. #8 
2. [x] Get ways and stats for ways. #3 
3. [x] Add total stats. #16 
4. [x] Error handling for overpass fail #17 
5. [x] Documentation. #7 
6. [ ] Offer data in .osm format - makes it easy to inspect in JOSM. #6

**Comment by ramyaragupathy** [comment]
Right now overpass query for way just returns a set of nodes without any coordinates in place. Consequently,this results in inappropriate geojson content, which also makes osm file conversion tricky.
Per voice w/ @planemad and @geohacker `offer data in .osm format` is not part of sprint 1.

**Comment by ramyaragupathy** [comment]
Merged through https://github.com/mapbox/osm-query/pull/13
